typography_spectrum: 0.35730379284359515
color:
  saturation: 0.564335094531998
  brandStrength: 0.16555545339360833
  lightness: 0.8314239922910929
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  rhythmicContrast: 0.11765825166366994
layout_spectrum: 0.18200066778808832
author:
  email: grid@w3box.com
  url: 'http://w3box.com'
name: w3box
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
