layout_spectrum: 0.18200066778808832
typography_spectrum: 0.35730379284359515
color:
  saturation: 0.564335094531998
  brandStrength: 0.16555545339360833
  lightness: 0.8314239922910929
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  rhythmicContrast: 0.11765825166366994
author:
  email: grid@w3box.com
  url: 'http://w3box.com'
name: w3box
navigation:
  - name: Evernote
    id: eb209d92-ed1d-4f53-a2fd-7e9c349b8475
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
