layout_spectrum: 0.7534656936768442
typography_spectrum: 0.13824704522266984
color:
  saturation: 0.39668539934791625
  brandStrength: 0.7579547788482159
  lightness: 0.8734487520996481
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  rhythmicContrast: 0.43008510838262737
author:
  email: grid@w3box.com
  url: 'http://w3box.com'
name: w3box
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
